export const functions = [
    { value: "", label: '' },
    { value: 2, label: 'JUDICIARIA' },
    { value: 4, label: 'ADMINISTRACAO' },
    { value: 10, label: 'SAUDE' },
    { value: 13, label: 'CULTURA' },
    { value: 15, label: 'URBANISMO' },
    { value: 16, label: 'HABITACAO' },
    { value: 21, label: 'ORGANIZACAO AGRARIA' },
    { value: 23, label: 'COMERCIO E SERVICOS' },
    { value: 24, label: 'COMUNICACOES' },
    { value: 28, label: 'ENCARGOS ESPECIAIS' },
    { value: 1, label: 'LEGISLATIVA' },
    { value: 3, label: 'ESSENCIAL A JUSTICA' },
    { value: 5, label: 'DEFESA NACIONAL' },
    { value: 6, label: 'SEGURANCA PUBLICA' },
    { value: 7, label: 'RELACOES EXTERIORES' },
    { value: 8, label: 'ASSISTENCIA SOCIAL' },
    { value: 9, label: 'PREVIDENCIA SOCIAL' },
    { value: 11, label: 'TRABALHO' },
    { value: 12, label: 'EDUCACAO' },
    { value: 14, label: 'DIREITOS DA CIDADANIA' },
    { value: 17, label: 'SANEAMENTO' },
    { value: 18, label: 'GESTAO AMBIENTAL' },
    { value: 19, label: 'CIENCIA E TECNOLOGIA' },
    { value: 20, label: 'AGRICULTURA' },
    { value: 22, label: 'INDUSTRIA' },
    { value: 25, label: 'ENERGIA' },
    { value: 26, label: 'TRANSPORTE' },
    { value: 27, label: 'DESPORTO E LAZER' },
    { value: 99, label: 'RESERVA DE CONTINGENCIA' },
];