export const subFunctions = [
    { value: "", label: '' },
    { value: 31, label: 'ACAO LEGISLATIVA' },
    { value: 32, label: 'CONTROLE EXTERNO' },
    { value: 92, label: 'REPRESENTACAO JUDICIAL E EXTRAJUDICIAL' },
    { value: 122, label: 'ADMINISTRACAO GERAL' },
    { value: 123, label: 'ADMINISTRACAO FINANCEIRA' },
    { value: 124, label: 'CONTROLE INTERNO' },
    { value: 125, label: 'NORMATIZACAO E FISCALIZACAO' },
    { value: 130, label: 'ADMINISTRACAO DE CONCESSOES' },
    { value: 131, label: 'COMUNICACAO SOCIAL' },
    { value: 151, label: 'DEFESA AREA' },
    { value: 211, label: 'RELACOES DIPLOMATICAS' },
    { value: 243, label: 'ASSISTENCIA A CRIANCA E AO ADOLESCENTE' },
    { value: 244, label: 'ASSISTENCIA COMUNITARIA' },
    { value: 271, label: 'PREVIDENCIA BASICA' },
    { value: 272, label: 'PREVIDENCIA DO REGIME ESTATUTARIO' },
    { value: 274, label: 'PREVIDENCIA ESPECIAL' },
    { value: 304, label: 'VIGILANCIA SANITARIA' },
    { value: 305, label: 'VIGILANCIA EPIDEMIOLOGICA' },
    { value: 331, label: 'PROTECAO E BENEFICIOS AO TRABALHADOR' },
    { value: 332, label: 'RELACOES DE TRABALHO' },
    { value: 361, label: 'ENSINO FUNDAMENTAL' },
    { value: 362, label: 'ENSINO MEDIO' },
    { value: 364, label: 'ENSINO SUPERIOR' },
    { value: 365, label: 'EDUCACAO INFANTIL' },
    { value: 366, label: 'EDUCACAO DE JOVENS E ADULTOS' },
    { value: 392, label: 'DIFUSAO CULTURAL' },
    { value: 422, label: 'DIREITOS INDIVIDUAIS' },
    { value: 482, label: 'HABITACAO URBANA' },
    { value: 543, label: 'RECUPERACAO DE AREAS DEGRADADAS' },
    { value: 544, label: 'RECURSOS HIDRICOS' },
    { value: 545, label: 'METEOROLOGIA' },
    { value: 571, label: 'DESENVOLVIMENTO CIENTIFICO' },
    { value: 572, label: 'DESENVOLVIMENTO TECNOLOGICO E ENGENHARIA' },
    { value: 604, label: 'DEFESA SANITARIA ANIMAL' },
    { value: 606, label: 'EXTENSAO RURAL' },
    { value: 607, label: 'IRRIGACAO' },
    { value: 609, label: 'DEFESA  AGROPECUARIA' },
    { value: 632, label: 'COLONIZACAO' },
    { value: 662, label: 'PRODUCAO INDUSTRIAL' },
    { value: 691, label: 'PROMOCAO COMERCIAL' },
    { value: 693, label: 'COMERCIO EXTERIOR' },
    { value: 694, label: 'SERVICOS FINANCEIROS' },
    { value: 695, label: 'TURISMO' },
    { value: 721, label: 'COMUNICACOES POSTAIS' },
    { value: 722, label: 'TELECOMUNICACOES' },
    { value: 751, label: 'CONSERVACAO DE ENERGIA' },
    { value: 781, label: 'TRANSPORTE AEREO' },
    { value: 783, label: 'TRANSPORTE FERROVIARIO' },
    { value: 785, label: 'TRANSPORTES ESPECIAIS' },
    { value: 811, label: 'DESPORTO DE RENDIMENTO' },
    { value: 847, label: 'TRANSFERENCIAS PARA EDUCACAO BASICA' },
    { value: 997, label: 'RESERVA DE RPPS' },
    { value: 999, label: 'RESERVA DE CONTINGENCIA' },
    { value: 61, label: 'ACAO JUDICIARIA' },
    { value: 62, label: 'DEFESA DO INTERESSE PUBLICO NO PROCESSO JUDICIARIO' },
    { value: 91, label: 'DEFESA DA ORDEM JURIDICA' },
    { value: 121, label: 'PLANEJAMENTO E ORCAMENTO' },
    { value: 126, label: 'TECNOLOGIA DA INFORMACAO' },
    { value: 127, label: 'ORDENAMENTO TERRITORIAL' },
    { value: 128, label: 'FORMACAO DE RECURSOS HUMANOS' },
    { value: 129, label: 'ADMINISTRACAO DE RECEITAS' },
    { value: 152, label: 'DEFESA NAVAL' },
    { value: 153, label: 'DEFESA TERRESTRE' },
    { value: 181, label: 'POLICIAMENTO' },
    { value: 182, label: 'DEFESA CIVIL' },
    { value: 183, label: 'INFORMACAO E INTELIGENCIA' },
    { value: 212, label: 'COOPERACAO INTERNACIONAL' },
    { value: 241, label: 'ASSISTENCIA AO IDOSO' },
    { value: 242, label: 'ASSISTENCIA AO PORTADOR DE DEFICIENCIA' },
    { value: 273, label: 'PREVIDENCIA COMPLEMENTAR' },
    { value: 301, label: 'ATENCAO BASICA' },
    { value: 302, label: 'ASSISTENCIA HOSPITALAR E AMBULATORIAL' },
    { value: 303, label: 'SUPORTE PROFILATICO E TERAPEUTICO' },
    { value: 306, label: 'ALIMENTACAO E NUTRICAO' },
    { value: 333, label: 'EMPREGABILIDADE' },
    { value: 334, label: 'FOMENTO AO TRABALHO' },
    { value: 363, label: 'ENSINO PROFISSIONAL' },
    { value: 367, label: 'EDUCACAO ESPECIAL' },
    { value: 368, label: 'EDUCACAO BASICA' },
    { value: 391, label: 'PATRIMONIO HISTORICO' },
    { value: 421, label: 'CUSTODIA E REINTEGRACAO SOCIAL' },
    { value: 423, label: 'ASSISTENCIA AOS POVOS INDIGENAS' },
    { value: 451, label: 'INFRA-ESTRUTURA URBANA' },
    { value: 452, label: 'SERVICOS URBANOS' },
    { value: 453, label: 'TRANSPORTES COLETIVOS URBANOS' },
    { value: 481, label: 'HABITACAO RURAL' },
    { value: 511, label: 'SANEAMENTO BASICO RURAL' },
    { value: 512, label: 'SANEAMENTO BASICO URBANO' },
    { value: 541, label: 'PRESERVACAO E CONSERVACAO AMBIENTAL' },
    { value: 542, label: 'CONTROLE AMBIENTAL' },
    { value: 573, label: 'DIFUSAO DO CONHECIMENTO CIENTIFICO E TECNOLOGICO' },
    { value: 601, label: 'PROMOCAO DA PRODUCAO VEGETAL' },
    { value: 602, label: 'PROMOCAO DA PRODUCAO ANIMAL' },
    { value: 603, label: 'DEFESA SANITARIA VEGETAL' },
    { value: 605, label: 'ABASTECIMENTO' },
    { value: 608, label: 'PROMOCAO DA PRODUCAO AGROPECUARIA' },
    { value: 631, label: 'REFORMA AGRARIA' },
    { value: 661, label: 'PROMOCAO INDUSTRIAL' },
    { value: 663, label: 'MINERACAO' },
    { value: 664, label: 'PROPRIEDADE INDUSTRIAL' },
    { value: 665, label: 'NORMALIZACAO E QUALIDADE' },
    { value: 692, label: 'COMERCIALIZACAO' },
    { value: 752, label: 'ENERGIA ELETRICA' },
    { value: 782, label: 'TRANSPORTE RODOVIARIO' },
    { value: 784, label: 'TRANSPORTE HIDROVIARIO' },
    { value: 812, label: 'DESPORTO COMUNITARIO' },
    { value: 813, label: 'LAZER' },
    { value: 841, label: 'REFINANCIAMENTO DA DIVIDA INTERNA' },
    { value: 842, label: 'REFINANCIAMENTO DA DIVIDA EXTERNA' },
    { value: 843, label: 'SERVICO DA DIVIDA INTERNA' },
    { value: 844, label: 'SERVICO DA DIVIDA EXTERNA' },
    { value: 845, label: 'OUTRAS TRANSFERENCIAS' },
    { value: 846, label: 'OUTROS ENCARGOS ESPECIAIS' },
];